kramdown:
  parse_block_html: true

# collections:
#   categories:
#     output: true

permalink: /blog/:categories/:year/:month/:day/:title/

defaults:
  # - scope:
  #     path: ""
  #     type: "categories"
  #   values:
  #     layout: "category"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
