title: "Ken-ichi's Website"
description: Ken-ichi Ueda's very real website for saying things.
url: https://kueda.net
author: Ken-ichi Ueda

kramdown:
  parse_block_html: true

# collections:
#   categories:
#     output: true

permalink: /blog/:categories/:year/:month/:day/:title/

defaults:
  # - scope:
  #     path: ""
  #     type: "categories"
  #   values:
  #     layout: "category"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll/scholar
  - jekyll-seo-tag
  - jekyll-feed

scholar:
  # TODO https://github.com/inukshuk/jekyll-scholar/issues/241 so we can sort
  # by author and editor
  sort_by: name

  # This includes the note bibtex field, which we can populate using the Extra
  # Zotero field for things like "Personal communication"
  style: apa-annotated-bibliography

  # Most CSLs that include a URL make no attempt to link that URL, so we're
  # doing that here
  bibliography_template: "{{ reference | linkify_urls }}"

  separate_links: true
